In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [2]:
df = sns.load_dataset("iris")

In [3]:
df.shape

(150, 5)

In [4]:
df.sample(5)

     sepal_length  sepal_width  petal_length  petal_width     species
116           6.5          3.0           5.5          1.8   virginica
26            5.0          3.4           1.6          0.4      setosa
24            4.8          3.4           1.9          0.2      setosa
91            6.1          3.0           4.6          1.4  versicolor
34            4.9          3.1           1.5          0.2      setosa

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [6]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [8]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [10]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [41]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [42]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [71]:
le = LabelEncoder()
encoded = le.fit_transform(y)

In [72]:
x_train,x_test,y_train,y_test = train_test_split(x, encoded, random_state = 42, test_size = 0.2)

In [73]:
scaler = StandardScaler()

In [74]:
x_train = scaler.fit_transform(x_train)

In [75]:
x_test = scaler.transform(x_test)

In [76]:
lr = LogisticRegression()

In [77]:
model_lr = lr.fit(x_train,y_train)

In [78]:
y_pred_lr = model_lr.predict(x_test)

In [79]:
accuracy_score(y_test,y_pred_lr)

1.0

In [80]:
rf = RandomForestClassifier()

In [81]:
model_rf = rf.fit(x_train,y_train)

In [82]:
y_pred_rf = model_rf.predict(x_test)

In [83]:
accuracy_score(y_test,y_pred_rf)

1.0

In [84]:
dt = DecisionTreeClassifier()

In [85]:
model_dt = dt.fit(x_train,y_train)

In [86]:
y_pred_dt = model_dt.predict(x_test)

In [87]:
accuracy_score(y_test,y_pred_dt)

1.0

In [88]:
knn = KNeighborsClassifier()

In [89]:
model_knn = knn.fit(x_train,y_train)

In [90]:
y_pred_knn = model_knn.predict(x_test)

In [91]:
accuracy_score(y_test,y_pred_knn)

1.0

In [92]:
svm = SVC()

In [93]:
model_svm = svm.fit(x_train,y_train)

In [94]:
y_pred_svm = model_svm.predict(x_test)

In [95]:
accuracy_score(y_test,y_pred_svm)

1.0